## Importing libraries

In [4]:
import mne
from pathlib import Path
%matplotlib qt

## Loading the data

In [2]:
base_dir = Path.cwd().parent
subject_dir = base_dir / "data" / "raw" / "V00test_data"   # Change directory
input_fname = subject_dir / "com_ruido.bdf"                # Change filename

raw = mne.io.read_raw_bdf(
    input_fname,
    eog=None,
    misc=None,
    stim_channel='auto',
    exclude=(),
    preload=True,
)

Extracting BDF parameters from /home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/raw/V00test_data/com_ruido.bdf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 12399999  =      0.000 ...   620.000 secs...


## Verify data structure

In [3]:
print(raw.info)
print('')
print(f'Channels: {len(raw.ch_names)}: {raw.ch_names}')
print('')
print(raw.annotations)

<Info | 8 non-empty values
 bads: []
 ch_names: Fp1, Fp2, F3, F4, C3, C4, P3, P4, O1, O2, F7, F8, T7, T8, P7, ...
 chs: 32 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 10000.0 Hz
 meas_date: 2025-10-24 11:04:23 UTC
 nchan: 32
 projs: []
 sfreq: 20000.0 Hz
 subject_info: <subject_info | his_id: Frederico_Possato, sex: 1, first_name: , last_name: , birthday: 1979-01-01>
>

Channels: 32: ['Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T7', 'T8', 'P7', 'P8', 'Pz', 'Iz', 'FC1', 'FC2', 'CP1', 'CP2', 'FC5', 'FC6', 'CP5', 'CP6', 'TP9', 'TP10', 'AFz', 'FCz', 'EOG', 'EMG']

<Annotations | 90 segments: Stimulus A (90)>


## Set EOG and EMG channels

In [4]:
raw.set_channel_types({
    'EOG': 'eog',
    'EMG': 'emg',
})

raw.set_montage('standard_1020')

<RawBDF | com_ruido.bdf, 32 x 12400000 (620.0 s), ~2.96 GiB, data loaded>

## Plot raw data

In [5]:
raw.plot(duration=5, n_channels=30, scalings='auto', block=False);

Using matplotlib as 2D backend.


In [6]:
raw.compute_psd().plot();

Effective window size : 0.102 (s)
Plotting power spectral density (dB=True).


In [7]:
raw.plot_sensors(show_names=True);

In [12]:
raw.compute_psd(fmin=1, fmax=40, method='welch').plot_topo();

Effective window size : 0.102 (s)


# Importing epochs

In [5]:
epochs = mne.read_epochs('/home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V00test/emg_processed/V00test_emg_epochs_processed.fif')


Reading /home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V00test/emg_processed/V00test_emg_epochs_processed.fif ...
    Found the data of interest:
        t =    -800.00 ...     799.67 ms
        0 CTF compensation matrices available
Not setting metadata
90 matching events found
No baseline correction applied
0 projection items activated


/tmp/ipykernel_55817/1200153175.py:1: RuntimeWarning: This filename (/home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V00test/emg_processed/V00test_emg_epochs_processed.fif) does not conform to MNE naming conventions. All epochs files should end with -epo.fif, -epo.fif.gz, _epo.fif or _epo.fif.gz
  epochs = mne.read_epochs('/home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V00test/emg_processed/V00test_emg_epochs_processed.fif')


In [13]:
epochs.plot(picks='emg')

In [11]:
print(epochs.annotations)

<Annotations | 90 segments: 8bits 1 (30), 8bits 2 (30), 8bits 3 (30)>


# Importing fif file

In [2]:
import mne
import numpy as np
raw = mne.io.read_raw_fif('/home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V02/processed/V02_raw_processed.fif', preload=False)
print(raw.info['ch_names'][-5:])
print(raw.annotations)
print(f"Total annotations: {len(raw.annotations)}")
print(f"Descriptions únicas: {np.unique(raw.annotations.description)}")

events, event_id = mne.events_from_annotations(raw)
print(f"\nTotal de eventos: {len(events)}")
print(f"Event IDs: {event_id}")
print(events[:20])

Opening raw data file /home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V02/processed/V02_raw_processed.fif...
    Range : 0 ... 15779999 =      0.000 ...   789.000 secs
Ready.
Opening raw data file /home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V02/processed/V02_raw_processed-1.fif...
    Range : 15780000 ... 31559999 =    789.000 ...  1578.000 secs
Ready.
Opening raw data file /home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V02/processed/V02_raw_processed-2.fif...
    Range : 31560000 ... 47339999 =   1578.000 ...  2367.000 secs
Ready.
Opening raw data file /home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V02/processed/V02_raw_processed-3.fif...
    Range : 47340000 ... 61829999 =   2367.000 ...  3091.500 secs
Ready.
['TP10', 'AFz', 'FCz', 'EOG', 'EMG']
<Annotations | 1136 segments: 8Bit 1 (134), 8Bit

/tmp/ipykernel_92639/3547273207.py:3: RuntimeWarning: This filename (/home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V02/processed/V02_raw_processed.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw = mne.io.read_raw_fif('/home/victormoraes/Documents/GitHub/TMS-EEG_ContextTree_Processing_and_Analysis/data/processed/V02/processed/V02_raw_processed.fif', preload=False)


Used Annotations descriptions: [np.str_('8Bit 1'), np.str_('8Bit 2'), np.str_('8Bit 3'), np.str_('Unk SW')]

Total de eventos: 1136
Event IDs: {np.str_('8Bit 1'): 1, np.str_('8Bit 2'): 2, np.str_('8Bit 3'): 3, np.str_('Unk SW'): 4}
[[ 534413       0       1]
 [ 658995       0       3]
 [ 795700       0       2]
 [ 918878       0       1]
 [1036464       0       3]
 [1184096       0       2]
 [1314143       0       1]
 [1433610       0       3]
 [1566921       0       2]
 [1694618       0       1]
 [1806497       0       3]
 [1954117       0       2]
 [2087873       0       1]
 [2235860       0       3]
 [2382279       0       2]
 [2495361       0       1]
 [2625873       0       3]
 [2772511       0       2]
 [2903795       0       1]
 [3015088       0       2]]


In [3]:
# 1. Sequência original SEM os Unk SW
mask_8bit = events[:, 2] != event_id['Unk SW']
events_8bit = events[mask_8bit]

print(f"Eventos 8Bit totais (sequência original): {len(events_8bit)}")
print(f"Primeiros 20 event IDs: {events_8bit[:20, 2]}")

# 2. Agora no objeto epochs (já carregado)
print(f"\nTotal epochs sobreviventes: {len(epochs)}")
print(f"Selection (primeiros 20): {epochs.selection[:20]}")
print(f"Total selection: {len(epochs.selection)}")

# 3. Verificar se o mapeamento bate
# epochs.selection deve indexar a sequência original de 8Bit
# Vamos conferir se os event IDs batem
for i in range(min(10, len(epochs))):
    idx_original = epochs.selection[i]
    print(f"Epoch {i}: selection={idx_original}, "
          f"epoch_event={epochs.events[i, 2]}, "
          f"original_event={events_8bit[idx_original, 2]}")


Eventos 8Bit totais (sequência original): 400
Primeiros 20 event IDs: [1 3 2 1 3 2 1 3 2 1 3 2 1 3 2 1 3 2 1 2]


NameError: name 'epochs' is not defined